limit_req_zone $binary_remote_addr zone=bs_provisioner:10m rate=10r/s;

log_format bs_provisioner_log
    '$time_iso8601 method=$request_method uri=$uri status=$status '
    'request_time=$request_time upstream_time=$upstream_response_time';

upstream bs_provisioner {
    server bs-provisioner:8080;
    keepalive 16;
}

server {
    listen 443 ssl;
    server_name _;
    server_tokens off;

    # whitelist
    # allow  123.456.789.000;
    deny all;

    ssl_certificate /etc/nginx/tls/server.crt;
    ssl_certificate_key /etc/nginx/tls/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    access_log /var/log/nginx/access.log bs_provisioner_log;

    client_max_body_size 16m;
    client_body_timeout 15s;
    limit_req_status 429;

    location / {
        limit_req zone=bs_provisioner burst=20 nodelay;

        proxy_pass http://bs_provisioner;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;

        proxy_connect_timeout 5s;
        proxy_send_timeout 35s;
        proxy_read_timeout 35s;
    }
}
